name: Our Quiet Days of Mayhem
description: |
  As Comedy Megacorp's grip on media and entertainment continues to tighten, Carl Leander and his rag-tag group of misfits struggle to keep the club open and fight off Comedy Megacorp.

  "Showbiz is a hideous bitch-godess" - George Burns.
characters:
  render: true
  description: |
    The characters
  list:
    -
      id: bob_shazbutt
      name: Bob Shazbutt
      age: 37
      occupation: Bartender
      role: lead
      images:
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/624/23108862960_b5cdce3674.jpg
          display: https://c1.staticflickr.com/1/624/23108862960_b5cdce3674_b.jpg
      description: |
        Kind of the central protagonist here. He himself is a comic artist, but is friends with a lot of comedians. Has the ability to huck anvils out of thin air. Went to art school but bartends at Zebtron's Comedy Club under owner Carl Leander.

        He's a bit like Ronnie Wood mixed with Bugs Bunny. He's a good 'ol boy at heart. He really tends to Carl Leander, kind of looks up to him as a father.
        > You gotta go low down crazy in order to get really wise

        ![](http://a142.idata.over-blog.com/1/59/44/42/pipol/ronnie_wood.jpg)
    -
      id: carl_leander
      name: Carl Leander
      age: 50
      occupation: Showhouse Impresario
      role: lead
      images:
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5657/23081488240_6ed44d6769.jpg
          display: https://c2.staticflickr.com/6/5657/23081488240_6ed44d6769_b.jpg
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/3/2025/1552840744_86e591a333.jpg
          display: https://c1.staticflickr.com/3/2025/1552840744_da87602026_o.jpg
      description: |
        A slavik man who got in showbiz early from his acrobatic parents. Has a twin brother Max Leander who runs a showbiz deli. They both ride tiny motorcycles (like Billy and Benny McCrary of Guiness fame). At their bar and diner, they sell their line of brews such as Carl Leander's Downtown Chunky: Heavy Beef Broth Porter.

        He's not a sleazebag like the other impresarios, often to his detriment. The other impresarios sometimes take advantage of him, and Bob has to come in a save the day.

        ![](http://2.bp.blogspot.com/-cBJadivJQbY/UGnYcfpqWNI/AAAAAAAADlw/1GreBJLP25s/s1600/twins.jpg)
        ![](http://i0.wp.com/goodsparkgarage.com/wp-content/uploads/2013/09/mcguiretwins_4.jpg)
        ![](http://dm9afq7zol1mi.cloudfront.net/naija.io/media/uploads/1098/fa3dfbd34d589081147544e9019fc812.jpg)
        Loosely based on Max Asnas:
        ![](http://4.bp.blogspot.com/-Wb9FTbLPJvc/ULojzy7AdOI/AAAAAAAAF4g/rbAz3OSDjaI/s1600/1955.gif)
    -
      id: rory_shazbutt
      name: Rory Shazbutt
      age: 25
      occupation: Comedian
      role: supporting
      description: |
        He is Bob's younger cousin by at least 12 years. He's been divorced. He has a bit of early Marc Maron syndrome in being a bit cantankerous and not having found that thread of love that comes after some age. He's still an angry young man, very bright. But his comedy is not for everyone.

        Bob gets it, but that's because they grew up together and thus have some in-jokes that only the 2 of them get.

        Rory has a bunch of older cousins, they love to drink Johnny walker. They corner him at family gatherings when they are drunk and offer him "advice." Get married Rory, c'mon you're 25.

        Rory starts seeing comedy as his almost one and only escape, do the detriment of being there for his family and friends.

        <img src="http://www.styleclicker.net/wp-content/uploads/2010/11/101115-Little-Red-Riding-Hood-Berlin-Rosenthaler-Strasse-12.jpg" class="portrait" />
        <img src="https://s-media-cache-ak0.pinimg.com/736x/ec/c0/e4/ecc0e42d229c58e963303071daa976cd.jpg" class="portrait" />
    -
      id: diedre_dukes
      name: Diedre Dukes
      age: 27
      occupation: Marketing, Comedy
      role: lead
      images:
        -
          orientation: landscape
          thumbnail: https://c2.staticflickr.com/6/5797/23512857276_1ece7c1b94.jpg
          display: https://c2.staticflickr.com/6/5797/23512857276_1ece7c1b94_b.jpg
      description: |
        She's one of those "I'm one of the guys" female comics. That's not a bad thing -- it's like Sarah Silverman or Amy Schumer. She scores jokes on herself about alcohol consumption and promiscuity a lot. She hangs with Bob and Rory on occassion.
    -
      id: don_sandwichbottom
      name: Don Sandwichbottom aka "[?] Rodney Dangerfield"
      occupation: Comedian, Odd Jobs
      role: supporting
      description: |
        This guy probably works harder than everyone. He's got some of that stand-off-ish unlikeability that Jack Roy must have had. He sells jokes out of the trunk of his car in front of the comedy club sometimes, otherwise he's involved in scamming the elderly in various jobs.

        Is a sweetheart but has broiling underlying temper issues. A bit hulk-like in that way. If you ask him to do something, he will grit his teeth and be like "sure I'd love to" and then punch a cat and kick an anvil across the room through the window.
    -
      id: emily_sandwichbottom
      name: Emily Sandwichbottom
      occupation: Comedian, Actress
      role: supporting
      description: |
        The sister of Don Sandwichbottom. She is attractive and ends up getting commercials more than success as a comedian. Other comedians hit on her but she's a little too smart for them. She and Bob are on and off, we are not sure if they are an item but she does make relationship-related jokes on stage that make you wonder. Or specifically, make Bob wonder.
        <img src="http://comedycentral.mtvnimages.com/images/NYCF/2014/ctw_2014_emmy_blotnick_02.jpg?" class="landscape" />
        <img src="http://33.media.tumblr.com/7ec8cee869e4f6bd56f1d1fb8505095c/tumblr_inline_n6nltodGX51qzp2h5.jpg" class="landscape" />
    -
      id: dobble
      name: Todd Dobber (Dobble)
      occupation: Stage Manager
      role: supporting
      description: |
        "I didn't do NOTHIN to NOBODY NOWHERE"

        He manages the stage for the show every night. He's always "got a guy" for whatever you need. He supplies the drugs.
    -
      id: larry_joe
      name: Larry Joe Cody Alouicious
      occupation: Product Designer, "Comedian"
      role: supporting
      description: |
        I mean he THINKS he his funny, that's what's important right? He's actually a product designer. All his jokes are like "What if Steve Jobs was in <latest Hollywood Release>?". He tries making fun of Android on stage. He does a lot of blow and drinks while at Zebtron's.
    -
      id: red_antoine
      name: Red Antoine
      occupation: Comedian
      role: other
      description: |
        A shock comedian. A hood comedian. He has a hell of a lot of confidence and douchiness. Chris Rock without the sense of humor or jokes really. More like Andrew Dice Clay.
    -
      id: popcorn_and_meatball
      name: Popcorn and Meatball
      occupation: Weed Enthusiasts
      role: other
      description: |
        They can be like statler and waldorf in the audience. They completely abuse marijuana in every stereotype worse than Cheech and Chong
    -
      id: tweetstream
      name: Tweetstream
      occupation: Superhero
      role: other
      images:
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5716/23513600996_2d21c5bb31.jpg
          display: https://c2.staticflickr.com/6/5716/23513600996_2d21c5bb31_b.jpg
      description: |
         Twitter's Superhero
    -
      id: zeitgeist
      name: Zeitgeist
      occupation: Superhero
      role: other
      images:
        -
          orientation: landscape
          thumbnail: https://c1.staticflickr.com/1/573/23255399750_5163fcb160.jpg
          display: https://c1.staticflickr.com/1/573/23255399750_5163fcb160_b.jpg
      description: |
        Google's Superhero
    -
      id: donald_dump
      name: Donald Dump
      occupation: Media Figure / Politician
      role: other
      images:
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/737/21453873383_c9aac82d60.jpg
          display: https://c1.staticflickr.com/1/737/21453873383_c9aac82d60_b.jpg
      description: |
         Raises Awareness of the Cornerstones of Luxury

         * Hunter Green And Black Marble
         * Gold Lame
         * Chandeliers
    -
      id: senator_radbod
      name: Senator Tony Radbod
      occupation: Media Figure / Politician
      role: other
      description: |
        * Hunky senator who has women swoon over him
        * Always worried whether he should be tweeting this or not
        * Bad at slang

        ![](http://i.huffpost.com/gen/811209/thumbs/s-PAUL-RYAN-WORKOUT-large640.jpg?6)
    -
      id: gary_sonnefeld
      name: Gary Sonnefeld
      occupation: Comedian
      role: other
      description: |
        He's blowing up, he's starting to headline. He pops in and does surprise sets which bumps lesser comedians. He belittles comedians, and has pompous slightly outdated views on the state of comedy.
    -
      id: jeb_leno
      name: Jeb Leno
      occupation: The UNDISCOVERED Host
      role: other
      images:
        -
          orientation: landscape
          thumbnail: https://c2.staticflickr.com/6/5335/18840884801_0614ddf5fa.jpg
          display: https://c2.staticflickr.com/6/5335/18840884801_0614ddf5fa_b.jpg
      description: |
        He started doing a late night talk show out of his garage. It started blowing up and affecting the viewership of the real talk shows. Hilarity ensues.
        Now this guy from Jersey burbs starts showing up at red carpet events. But he's a good guy. Because of the word "undiscovered" in his tagline, he gets more gigs and tastemaker attention than he probably should.
      notes: >
        Too much of a Tom Green situation?
    -
      name: ???
      occupation: Producer
      role: other
      status: idea
      description: |
        A Lorne Michaels type that comes to Zebtron's sometimes to scope out talent.
    -
      name: ???
      occupation: Talent Agent
      role: supporting
      status: idea
      description: |
        He's always hanging around the joint
    -
      name: ???
      occupation: Star TV Chef
      role: other
      status: idea
      description: |
        ???
    -
      name: ???
      occupation: Ghost, Comedian
      role: other
      status: idea
      description: |
        the ghost of Sheky Greene type infamous comic
    - name: ???
      occupation: Ghost, Comedian
      role: other
      status: idea
      description: |
        the ghost of Lenny Brucy who still thinks he is edgy and shocking
themes:
  render: true
  list:
    -
      name: Sponsorship and art
      description: |
        Groucho Marx on the relationship between sponsorship and comedy.ï»¿ [[youtube](https://www.youtube.com/watch?v=xjUUOyS2j3Q)]
        <iframe src="https://www.youtube.com/embed/xjUUOyS2j3Q" frameborder="0" allowfullscreen></iframe>
    -
      name: State of Comedy
      status: idea
      description: |
        Comedy good and bad. Standup, television, Saturday Night Live. SNL especially politicians vying to get on the show for their own PR benefits.
    -
      name: Drugs
      status: idea
      description: |
        Societal attitudes toward substance use and abuse. People that traffic stereotypes.
    -
      name: State of Pop Culture
      status: idea
      description: |
        What passes for popular culture. What people consume without even thinking about it. This aspect is probably about fake shows and ads.
inspirations:
  render: true
  description: |
    Visual and stylistic inspirational sources
  list:
    -
      name: F is for Family
      type: netflix original animated series
      description: |
        It's Bill Burr's show, it's his humor. There are some REAL twisted scenes

        * Billy hearing his parents have sex
        * first experience in the mens roon
        * Sue crying with plastic bowl on head with dog humping her leg.

        But in the end there is real heart in the show. The kids, the relationship with the parents. It's all really good. The characters are great.
    -
      name: Silicon Valley
      type: live action tv series
      description: |
        The show's subtle character nuances are what drive the comedy. It's not so much mockery, but played with a realism and commitment to the character by the actors which is what drives the comedy.
    -
      name: Tiny Toons / Animaniacs
      type: animated tv series
      description: |
        These 2 animated series' constant allusions to showbiz and Hollywood give a level of self-referential consciousness, and then it uses violent cartoon mayhem to break it up.
        [Article](http://www.justpressplay.net/reviews/10440-animaniacs-volume-4.html "Animaniacs Volume 4")
    -
      name: Looney Toons
      type: animated tv series
      description: |
        All the showbiz stuff, like [this episode](https://en.wikipedia.org/wiki/Show_Biz_Bugs "Show Biz Bugs") classic Bugs vs Daffy showbiz rivalry
    -
      name: It's Always Sunny
      type: live action tv series
      description: |
        The rag-tag gang of misfits and their weird father-figure.
    -
      name: The Comedians
      type: book
      description: |
        by Kliph Nesteroff [[blog](http://classicshowbiz.blogspot.com/)]

        This book has so much info about the history of comedy. There are amazing and interesting stories about comedians and their lives. The stuff about all hanging out in the drug store not buying anything but using the payphones to talk to their managers and agents whose offices were just upstairs. This is all at around 50th st and Broadway in 1950's Manhattan, which is the time that should be referenced for visual design. Also other high style product/interior designs from the 1950s.

        The stuff about the Marx Brothers riding the rails to get to their gigs across the nation. The rise of fall of entertainment stars with evolving media (radio and television).
    -
      name: Red Meat
      type: comic
      description: |
        It is such a weird comic book. Dark humor abound.
    -
      name: American Pop
      type: animated movie
      description: |
        It's about showbiz, has a chaotic yet refined look.
plots:
  render: true
  description: plotline, episode and story arc ideas
  list:
    -
      name: ???
      type: Short
      status: idea
      description: |
        Bob walks Mega-Old-Lady across the street and is astounded because he only thinks that happens on TV.
    -
      name: Charles Brownson in: The Rhythm Bandit
      type: Short
      status: idea
      description: |
        **synopsis**

        * Charles Brownson is lusting after a lady at a bar
        * He checks her out, does a little indian eye side-to-side thing
        * He tries talking to her
        * She stabs him, breaks glass on him, shoots him, he makes really awful painful sounds. It makes Indian fight sounds. She seriously berates him and belittles him and imasculates him to the point of abuse.
        * Finally, wounded, he gets out on the dance floor, does something with indian music and tablas and all
        * she ends up falling for him
        * heart wipe out

        **elements:**

        * mickey and minnie
        * pepe le pew
    -
      name: ???
      type: Episode
      status: idea
      description: |
        Larry does a set about how Android sucks and the crowd doesn't respond do great so he resorts to doing more drugs then going on stage.
    -
      name: ???
      type: Episode
      status: idea
      description: |
        Emily does a set about relationships and Bob thinks she is talking about him.
    -
      name: ???
      type: Episode
      status: idea
      description: |
        Rory hits on Emily but fails. Then he does a set that is too smart and the audience doesn't respond well, he denegrates them. It's not good. Bob tells him.
    -
      name: Megacorp encroaches
      type: Story Arc
      status: idea
      description: |
        Comedy Megacorp snatches up comedy clubs and television stations with it's terrible comedy.
locations:
  render: true
  description: |
    A weird mix between Vegas, NYC, and LA.
  list:
    -
      name: Bronson Pinchot's Balki's
      type: showbiz bar
      description: |
        A schmaltzy showbiz bar celebrating the career of Bronson Pinchot. It's like a Ukranian wedding hall.
    -
      name: Zebtron's
      type: comedy club
      description: |
        This one is owned by Zebtron himself who we see little of but his hand is felt.
    -
      name: Max's Diner
      type: restaurant
      description: |
        The caste-system of comedians applies here. Best tables to the top billing.
        <img src="http://4.bp.blogspot.com/-Dy9dSsSzPfw/ULoMsD4i-lI/AAAAAAAAF1I/52qfzF5ms68/s1600/sate+hirsch.jpg" class="landscape" />
        Based on [Stage Deli](http://drewfriedman.blogspot.com/2012/12/farewell-stage-deli.html)
    -
      name: Bob's Apartment
      type: apartment
      description: |
        Bob lives here. A lot of the direct-to-camera dialogue happens here.
    -
      name: Midtown Streets
      type: neighborhood
      description: |
        People watching. Showbiz haunts. Agents, comedians, other showbiz types.
    -
      name: Village Streets
      type: neighborhood
      description: |
        Dingy bars, clubs. Party people.
    -
      name: Paul's Da Burger Joint
      type: restaurant
      description: |
        burger joint
    -
      name: Superknees
      type: bar
      description: |
        A bouncy castle bar
    -
      name: Two Stool Beaver
      type: bar
      description: |
        Another gag bar
    -
      name: ???
      type: comedy club
      status: idea
      description: |
        The "underground" comedy club
    -
      name: ???
      type: Airport
      status: idea
      description: |
        Comedians travel through here and we see inside their heads trying out new airport material but they always talk themselves out of it.
concept_art:
  render: true
  list:
    -
      id: 10001
      name: At the showbiz bar
      status: idea
      description: |
        Bob bartending Carl Leander's showbiz bar
    -
      id: 10002
      name: Selling jokes from the trunk
      status: idea
      description: |
        Don Sandwichbottom selling jokes from his trunk
    -
      id: 10003
      name: Street view
      status: idea
      description: |
        Hangin in the streets a la Hansons Drug Store
    -
      id: 10004
      name: Comedy Megacorp offices
      status: idea
      description: |
        Inside the beast
